import { rawSql } from '@/infrastructure/db/client';
import { Money } from '@/financial-engine/money';
import { calculatePercentage } from '@/financial-engine/percentage';

export type CycleReviewCategory={categoryId:string;name:string;allocationType:string;planned:string;actual:string;variance:string;variancePercent:number|null;status:'OVER'|'UNDER'|'ON_TRACK'|'UNUSED';needsExplanation:boolean;context:null|{persistence:'TEMPORARY'|'RECURRING'|'PERMANENT';direction:'LOWER'|'NORMAL'|'HIGHER';reasonCodes:string[];customReason:string|null;seasonCode:string|null;customSeasonName:string|null;useForNextPlan:boolean}};
export type CycleReviewRecommendation={categoryId:string|null;name:string;currentAmount:string;suggestedAmount:string;action:'KEEP'|'INCREASE'|'REDUCE'|'PAUSE'|'ADD';reason:string;evidence:'CURRENT_PLAN'|'USER_CONFIRMED_PERMANENT_CHANGE'|'REVIEW_REQUIRED'};
const SIGNIFICANT_VARIANCE_PERCENT=10;
function normalizeSavedRecommendation(value:unknown):CycleReviewRecommendation|null{if(!value||typeof value!=='object')return null;const r=value as Record<string,unknown>;const action=String(r.action??'KEEP');if(!['KEEP','INCREASE','REDUCE','PAUSE','ADD'].includes(action))return null;const e=String(r.evidence??'CURRENT_PLAN');return{categoryId:r.categoryId==null?null:String(r.categoryId),name:String(r.name??''),currentAmount:String(r.currentAmount??'0.00'),suggestedAmount:String(r.suggestedAmount??r.currentAmount??'0.00'),action:action as CycleReviewRecommendation['action'],reason:String(r.reason??''),evidence:(['CURRENT_PLAN','USER_CONFIRMED_PERMANENT_CHANGE','REVIEW_REQUIRED'].includes(e)?e:'CURRENT_PLAN') as CycleReviewRecommendation['evidence']};}

export async function getCycleMonthlyReview(userId:string,cycleId:string){
 const cycleRows=await rawSql`select id,name,start_date::text,expected_next_income_date::text,status from public.financial_cycles where id=${cycleId} and user_id=${userId} limit 1`; const cycle=cycleRows[0];if(!cycle)return null;
 const [bankRows,catRows,recurringRows,savedRows]=await Promise.all([
  rawSql`select count(*) filter(where status in ('PARSING','REVIEW','READY'))::int open_imports,coalesce(sum(review_count) filter(where status in ('REVIEW','READY')),0)::int unresolved,count(*) filter(where status='APPROVED' and reconciliation_status='MATCHED')::int matched,count(*) filter(where status='APPROVED' and reconciliation_status<>'MATCHED')::int unmatched from public.bank_statement_imports where user_id=${userId} and account_id in (select id from public.accounts where user_id=${userId}) and coalesce(period_end,period_start,created_at::date)>=${String(cycle.start_date)}::date and coalesce(period_start,period_end,created_at::date)<=${String(cycle.expected_next_income_date)}::date`,
  rawSql`with current_plan as (select p.current_version_id from public.financial_plans p where p.user_id=${userId} and p.cycle_id=${cycleId} limit 1),planned as (select ba.category_id,c.name,ba.allocation_type,ba.planned_amount from public.budget_allocations ba join public.budget_categories c on c.id=ba.category_id and c.user_id=${userId} where ba.plan_version_id=(select current_version_id from current_plan)),actual as (select category_id,coalesce(sum(amount),0) amount from public.transactions where user_id=${userId} and cycle_id=${cycleId} and status='POSTED' and transaction_type='EXPENSE' group by category_id) select p.category_id,p.name,p.allocation_type,p.planned_amount::text,coalesce(a.amount,0)::text actual_amount,ctx.direction,ctx.reason_codes,ctx.custom_reason,ctx.persistence,ctx.season_code,ctx.custom_season_name,ctx.use_for_next_plan from planned p left join actual a on a.category_id=p.category_id left join public.cycle_category_contexts ctx on ctx.user_id=${userId} and ctx.cycle_id=${cycleId}::uuid and ctx.category_id=p.category_id order by p.name`,
  rawSql`select count(*)::int n from public.bank_statement_rows r join public.bank_statement_imports i on i.id=r.import_id and i.user_id=r.user_id where r.user_id=${userId} and r.recurring_candidate=true and r.transaction_date>=${String(cycle.start_date)}::date and r.transaction_date<${String(cycle.expected_next_income_date)}::date`,
  rawSql`select status,next_cycle_recommendations,user_notes,reviewed_at::text from public.cycle_monthly_reviews where user_id=${userId} and cycle_id=${cycleId} limit 1`
 ]);
 const categories:CycleReviewCategory[]=catRows.map(r=>{const planned=Money.parse(String(r.planned_amount??'0')),actual=Money.parse(String(r.actual_amount??'0')),variance=planned.subtract(actual);const variancePercent=planned.isPositive()?Number(calculatePercentage(actual.subtract(planned).minorUnits,planned.minorUnits)?.percent??'0'):null;const abs=variancePercent==null?0:Math.abs(variancePercent);const status:CycleReviewCategory['status']=actual.isZero()&&planned.isPositive()?'UNUSED':abs<SIGNIFICANT_VARIANCE_PERCENT?'ON_TRACK':actual.compare(planned)>0?'OVER':'UNDER';const context=r.persistence?{persistence:String(r.persistence) as 'TEMPORARY'|'RECURRING'|'PERMANENT',direction:String(r.direction) as 'LOWER'|'NORMAL'|'HIGHER',reasonCodes:Array.isArray(r.reason_codes)?r.reason_codes.map(String):[],customReason:r.custom_reason?String(r.custom_reason):null,seasonCode:r.season_code?String(r.season_code):null,customSeasonName:r.custom_season_name?String(r.custom_season_name):null,useForNextPlan:Boolean(r.use_for_next_plan)}:null;return{categoryId:String(r.category_id),name:String(r.name),allocationType:String(r.allocation_type),planned:planned.toString(),actual:actual.toString(),variance:variance.toString(),variancePercent,status,needsExplanation:abs>=SIGNIFICANT_VARIANCE_PERCENT&&!context,context};});
 const generatedRecommendations:CycleReviewRecommendation[]=categories.map(c=>{const planned=Money.parse(c.planned),actual=Money.parse(c.actual);if(c.context?.useForNextPlan&&c.context.persistence==='PERMANENT'&&c.variancePercent!=null&&Math.abs(c.variancePercent)>=SIGNIFICANT_VARIANCE_PERCENT){return{categoryId:c.categoryId,name:c.name,currentAmount:c.planned,suggestedAmount:c.actual,action:(actual.compare(planned)>0?'INCREASE':'REDUCE') as 'INCREASE'|'REDUCE',reason:'التغيير مقترح لأنك صنفت الانحراف كتغير دائم وسمحت باستخدامه في التخطيط القادم. لا يوجد تقريب أو زيادة إضافية.',evidence:'USER_CONFIRMED_PERMANENT_CHANGE'};}if(c.needsExplanation)return{categoryId:c.categoryId,name:c.name,currentAmount:c.planned,suggestedAmount:c.planned,action:'KEEP',reason:'يوجد انحراف 10% أو أكثر، لكن لا يوجد تفسير معتمد يبرر تغيير الميزانية القادمة.',evidence:'REVIEW_REQUIRED'};if(c.context?.persistence==='TEMPORARY')return{categoryId:c.categoryId,name:c.name,currentAmount:c.planned,suggestedAmount:c.planned,action:'KEEP',reason:'الانحراف مسجل كتغير مؤقت، لذلك لا يستخدم وحده لتغيير الميزانية القادمة.',evidence:'CURRENT_PLAN'};if(c.context?.persistence==='RECURRING')return{categoryId:c.categoryId,name:c.name,currentAmount:c.planned,suggestedAmount:c.planned,action:'KEEP',reason:'الانحراف متكرر/موسمي، ويلزم أن ينطبق سببه على الدورة القادمة قبل تغيير المبلغ.',evidence:'REVIEW_REQUIRED'};return{categoryId:c.categoryId,name:c.name,currentAmount:c.planned,suggestedAmount:c.planned,action:'KEEP',reason:'لا يوجد سبب موثق يبرر تغيير هذا البند.',evidence:'CURRENT_PLAN'};});
 const b=bankRows[0]??{};const recurring=Number(recurringRows[0]?.n??0);const saved=savedRows[0];const savedRecommendations=Array.isArray(saved?.next_cycle_recommendations)?saved.next_cycle_recommendations.map(normalizeSavedRecommendation).filter(Boolean) as CycleReviewRecommendation[]:[];
 return{cycle:{id:String(cycle.id),name:String(cycle.name),startDate:String(cycle.start_date),expectedNextIncomeDate:String(cycle.expected_next_income_date),status:String(cycle.status)},bank:{openImports:Number(b.open_imports??0),unresolved:Number(b.unresolved??0),matched:Number(b.matched??0),unmatched:Number(b.unmatched??0),ready:Number(b.open_imports??0)===0&&Number(b.unresolved??0)===0&&Number(b.unmatched??0)===0},categories,recurringCandidates:recurring,recommendations:savedRecommendations.length?savedRecommendations:generatedRecommendations,saved:saved?{status:String(saved.status),recommendations:savedRecommendations,notes:saved.user_notes?String(saved.user_notes):'',reviewedAt:saved.reviewed_at?String(saved.reviewed_at):null}:null};
}
