import { Money } from '@/financial-engine/money';

const uuidLike=/^[0-9a-f-]{32,36}$/i;
const amountLike=/^\d{1,16}(?:\.\d{1,2})?$/;
const dateLike=/^\d{4}-\d{2}-\d{2}$/;

export interface ConfigureEmergencyFundInput { name?:string; targetAmount:string; }
export interface EmergencyContributionInput { emergencyFundId:string; emergencyAllocationId?:string; fromAccountId:string; toAccountId:string; amount:string; transactionDate:string; description?:string; idempotencyKey:string; }
export interface EmergencyWithdrawalInput { emergencyFundId:string; fromAccountId:string; toAccountId:string; amount:string; transactionDate:string; reason:string; emergencyType:string; description?:string; idempotencyKey:string; }
export type Validation<T>={success:true;data:T}|{success:false;message:string};
function money(v?:string){if(!v||!amountLike.test(v))return null;try{const m=Money.parse(v);return m.isPositive()?m.toString():null}catch{return null}}
export function validateConfigureEmergencyFund(i:Partial<ConfigureEmergencyFundInput>):Validation<ConfigureEmergencyFundInput>{const a=money(i.targetAmount);if(!a)return{success:false,message:'هدف صندوق الطوارئ يجب أن يكون مبلغًا أكبر من صفر.'};return{success:true,data:{name:i.name?.trim()||'صندوق الطوارئ',targetAmount:a}}}
export function validateEmergencyContribution(i:Partial<EmergencyContributionInput>):Validation<EmergencyContributionInput>{if(!i.emergencyFundId||!uuidLike.test(i.emergencyFundId))return{success:false,message:'صندوق الطوارئ غير صالح.'};if(i.emergencyAllocationId&&!uuidLike.test(i.emergencyAllocationId))return{success:false,message:'تخصيص الطوارئ غير صالح.'};if(!i.fromAccountId||!uuidLike.test(i.fromAccountId)||!i.toAccountId||!uuidLike.test(i.toAccountId)||i.fromAccountId===i.toAccountId)return{success:false,message:'يجب اختيار حسابين مختلفين وصالحين.'};const a=money(i.amount);if(!a)return{success:false,message:'مبلغ المساهمة غير صالح.'};if(!i.transactionDate||!dateLike.test(i.transactionDate))return{success:false,message:'تاريخ المساهمة مطلوب.'};if(i.description&&i.description.trim().length>1000)return{success:false,message:'الوصف طويل جدًا.'};if(!i.idempotencyKey?.trim()||i.idempotencyKey.trim().length>200)return{success:false,message:'مفتاح منع التكرار غير صالح.'};return{success:true,data:{emergencyFundId:i.emergencyFundId,emergencyAllocationId:i.emergencyAllocationId,fromAccountId:i.fromAccountId,toAccountId:i.toAccountId,amount:a,transactionDate:i.transactionDate,description:i.description?.trim()||undefined,idempotencyKey:i.idempotencyKey.trim()}}}
export function validateEmergencyWithdrawal(i:Partial<EmergencyWithdrawalInput>):Validation<EmergencyWithdrawalInput>{if(!i.emergencyFundId||!uuidLike.test(i.emergencyFundId))return{success:false,message:'صندوق الطوارئ غير صالح.'};if(!i.fromAccountId||!uuidLike.test(i.fromAccountId)||!i.toAccountId||!uuidLike.test(i.toAccountId)||i.fromAccountId===i.toAccountId)return{success:false,message:'يجب اختيار حسابين مختلفين وصالحين.'};const a=money(i.amount);if(!a)return{success:false,message:'مبلغ السحب غير صالح.'};if(!i.transactionDate||!dateLike.test(i.transactionDate))return{success:false,message:'تاريخ السحب مطلوب.'};if(!i.reason?.trim()||i.reason.trim().length>1000)return{success:false,message:'سبب السحب من الطوارئ غير صالح.'};if(!i.emergencyType?.trim()||i.emergencyType.trim().length>160)return{success:false,message:'نوع حالة الطوارئ غير صالح.'};if(i.description&&i.description.trim().length>1000)return{success:false,message:'الوصف طويل جدًا.'};if(!i.idempotencyKey?.trim()||i.idempotencyKey.trim().length>200)return{success:false,message:'مفتاح منع التكرار غير صالح.'};return{success:true,data:{emergencyFundId:i.emergencyFundId,fromAccountId:i.fromAccountId,toAccountId:i.toAccountId,amount:a,transactionDate:i.transactionDate,reason:i.reason.trim(),emergencyType:i.emergencyType.trim(),description:i.description?.trim()||undefined,idempotencyKey:i.idempotencyKey.trim()}}}
