import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAuthenticatedUser } from '@/auth/require-authenticated-user';
import { getBankStatementImport } from '@/features/bank-statements/queries/get-import';
import { listBudgetCategories } from '@/features/budget-categories/queries/list-budget-categories';
import { listAccounts } from '@/features/accounts/queries/list-accounts';
import { listActiveFundingCases } from '@/features/internal-funding/queries/list-active-funding-cases';
import { Money, sumMoney } from '@/financial-engine/money';
import { formatSar } from '@/lib/format-money';
import { WorkflowStageGuide } from '@/components/ux/workflow-stage-guide';
import { approveBankStatementImportAction, reviewBankStatementRowAction } from '../actions';

const KIND:Record<string,string>={EXPENSE:'مصروف',INCOME:'دخل',TRANSFER:'تحويل',REFUND:'استرداد',FEE:'رسوم',UNKNOWN:'غير معروف'};
const SOURCE:Record<string,string>={HEURISTIC:'تحليل أولي',MERCHANT_RULE:'ذاكرة التاجر',INTERNAL_TRANSFER:'تحويل داخلي',DUPLICATE_MATCH:'مطابقة محتملة',USER:'تأكيدك'};
export default async function BankStatementReviewPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;approved?:string}>}) {
  const user = await requireAuthenticatedUser();
  const {id}=await params;
  const [data,categories,accounts,fundingCases,q]=await Promise.all([getBankStatementImport(user.id,id),listBudgetCategories(user.id,false),listAccounts(user.id),listActiveFundingCases(user.id),searchParams]);
  if(!data) notFound();
  const imp=data.import;
  const rows=data.rows;
  const debitTotal=sumMoney(rows.filter(r=>r.direction==='DEBIT').map((r)=>Money.parse(String(r.amount))));
  const creditTotal=sumMoney(rows.filter(r=>r.direction==='CREDIT').map((r)=>Money.parse(String(r.amount))));
  const needs=rows.filter(r=>r.reviewStatus==='NEEDS_REVIEW').length;
  return <main className="page-shell bank-statements-page p47-closure-page" dir="rtl">
    <header className="page-header p47-closure-header"><div><p className="eyebrow">مراجعة ذكية</p><div className="title-with-help"><h1>{imp.file_name}</h1></div></div><Link className="button-link" href="/bank-statements">كل الكشوف</Link></header>
    <WorkflowStageGuide ariaLabel="مراحل مراجعة كشف الحساب" stages={[
      {label:'1. قراءة الملخص',description:'راجع إجمالي العمليات والمبالغ',state:'done'},
      {label:'2. حسم الاستثناءات',description:'ركز فقط على العمليات التي تحتاج قرارك',state:needs>0?'current':'done'},
      {label:'3. اعتماد الكشف',description:'يظهر بعد حسم كل الاستثناءات',state:needs===0&&String(imp.status)!=='APPROVED'?'current':'next'},
      {label:'4. المصالحة',description:'قارن رصيد البنك برصيد النظام',state:String(imp.status)==='APPROVED'?'current':'next'},
    ]}/>
    {q.error?<p className="error-banner" role="alert">{q.error}</p>:null}
    {q.approved?<p className="success-banner" role="status">تم اعتماد كشف الحساب وتحديث السجل المالي.</p>:null}
    <section className="statement-kpis p75-primary-metrics"><div><span>الحساب</span><strong>{imp.bankName?`${imp.bankName} · `:''}{imp.accountName}</strong></div><div><span>تحتاج مراجعة</span><strong>{needs}</strong></div><div><span>الخصم</span><strong>{formatSar(debitTotal.toString())}</strong></div><div><span>الإضافة</span><strong>{formatSar(creditTotal.toString())}</strong></div></section>
    {needs>0?<section className="card"><div className="section-title-row"><h2>قرارات تحتاجك</h2></div><div className="p44-review-list">{rows.filter(r=>r.reviewStatus==='NEEDS_REVIEW').map((r)=><form action={reviewBankStatementRowAction} className="form-card" key={r.id}><input type="hidden" name="importId" value={id}/><input type="hidden" name="rowId" value={r.id}/><div className="section-title-row"><div><strong>{r.description}</strong><div className="muted">{r.transactionDate??'بدون تاريخ'} · {r.direction==='DEBIT'?'خصم':'إضافة'} · {formatSar(String(r.amount))}</div></div><span>{Number(r.confidence).toFixed(0)}%</span></div><div className="form-grid"><label>نوع العملية<select name="detectedKind" defaultValue={r.detectedKind}><option value="EXPENSE">مصروف</option><option value="INCOME">دخل</option><option value="TRANSFER">تحويل</option><option value="REFUND">استرداد</option><option value="FEE">رسوم</option><option value="UNKNOWN">غير معروف</option></select></label><label>التصنيف<select name="categoryId" defaultValue={r.categoryId??''}><option value="">بدون تصنيف</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>الحساب المقابل<select name="matchedAccountId" defaultValue={r.matchedAccountId??''}><option value="">ليس تحويلًا داخليًا</option>{accounts.filter(a=>a.isActive&&a.id!==imp.account_id).map(a=><option key={a.id} value={a.id}>{a.bankName?`${a.bankName} · `:''}{a.name}</option>)}</select></label><label>اسم التاجر المعروف<input name="displayName" defaultValue={r.normalizedMerchant??''} maxLength={160}/></label><label>تابع لتمويل/رحلة؟<select name="fundingCaseId" defaultValue={r.fundingCaseId??''}><option value="">لا</option>{fundingCases.filter(f=>f.status!=='RECOVERY').map(f=><option key={f.id} value={f.id}>{f.title}{f.destinationCity?` · ${f.destinationCity}`:''}</option>)}</select></label><label className="full"><input type="checkbox" name="remember" defaultChecked={Boolean(r.normalizedMerchant)}/> تذكّر هذا التاجر والتصنيف للمرة القادمة</label></div>{Number(r.matchingPendingCount??0)>0?<div className="merchant-batch-preview"><strong>يوجد {Number(r.matchingPendingCount)} عملية أخرى مطابقة لنفس اسم التاجر</strong><span>إجمالي العمليات المطابقة الأخرى: {formatSar(String(r.matchingPendingTotal??'0'))}</span></div>:null}<div className="button-row"><button className="primary-button" type="submit" name="applyScope" value="THIS_ONLY">تأكيد هذه العملية</button>{Number(r.matchingPendingCount??0)>0?<button className="secondary-button" type="submit" name="applyScope" value="EXACT_MATCHES">تأكيد التعريف على العمليات المطابقة</button>:null}</div></form>)}</div></section>:null}

    {String(imp.status)==='APPROVED'?<section className="card reconciliation-card"><div className="section-title-row"><h2>المصالحة البنكية</h2><span className={`p44-kind ${imp.reconciliation_status==='MATCHED'?'is-auto':'needs-review'}`}>{imp.reconciliation_status==='MATCHED'?'مطابق 100%':imp.reconciliation_status==='DIFFERENCE'?'يوجد فرق':'لم يُدخل رصيد البنك'}</span></div><div className="statement-kpis"><div><span>رصيد البنك</span><strong>{imp.closing_balance==null?'—':formatSar(String(imp.closing_balance))}</strong></div><div><span>رصيد النظام</span><strong>{formatSar(String(imp.reconciliation_system_balance??'0'))}</strong></div><div><span>الفرق</span><strong>{imp.reconciliation_difference==null?'—':formatSar(String(imp.reconciliation_difference))}</strong></div><div><span>عمليات أُنشئت</span><strong>{imp.approved_transaction_count??0}</strong></div><div><span>مطابقات لم تُكرر</span><strong>{imp.ignored_row_count??0}</strong></div></div></section>:needs===0?<section className="card"><div className="section-title-row"><h2>اعتماد كشف الحساب</h2></div><form action={approveBankStatementImportAction} className="form-card"><input type="hidden" name="importId" value={id}/><label>الرصيد الختامي في كشف البنك<input name="closingBalance" inputMode="decimal" placeholder="مثال: 5913.44"/></label><button className="primary-button" type="submit">اعتماد الكشف وإنشاء العمليات</button></form></section>:null}
    <details className="ux-progressive-disclosure p75-secondary-section"><summary>عرض جميع العمليات المحللة ({rows.length})</summary><div className="ux-progressive-disclosure__content"><section className="card"><div className="section-title-row"><h2>العمليات المحللة</h2></div>
      <div className="transaction-table-wrap"><table className="transaction-table"><thead><tr><th>#</th><th>التاريخ</th><th>البيان</th><th>النوع</th><th>المصدر</th><th>الثقة</th><th>المبلغ</th></tr></thead><tbody>{rows.map((r)=><tr key={r.id} className={r.reviewStatus==='NEEDS_REVIEW'?'needs-review-row':''}><td data-label="#">{r.rowNumber}</td><td data-label="التاريخ">{r.transactionDate ?? '—'}</td><td data-label="البيان"><strong>{r.description}</strong>{r.normalizedMerchant?<small className="muted">{r.normalizedMerchant}</small>:null}{r.duplicateCandidate?<small className="p44-alert">مطابقة محتملة مع عملية مسجلة{r.matchedTransactionDescription?` · ${r.matchedTransactionDescription}`:''}</small>:null}{r.matchedAccountName?<small className="p44-success">تحويل محتمل إلى: {r.matchedAccountName}</small>:null}{r.categoryName?<small className="muted">التصنيف: {r.categoryName}</small>:null}{r.recurringCandidate?<small className="p44-recurring">نمط متكرر محتمل · تقريبًا كل {r.recurringIntervalDays??'—'} يوم · ثقة {Number(r.recurringScore??0).toFixed(0)}%</small>:null}</td><td data-label="النوع"><span className={`p44-kind ${r.reviewStatus==='NEEDS_REVIEW'?'needs-review':'is-auto'}`}>{KIND[r.detectedKind] ?? r.detectedKind}</span></td><td data-label="المصدر"><strong>{SOURCE[r.decisionSource]??r.decisionSource}</strong>{r.decisionReason?<small className="muted">{r.decisionReason}</small>:null}</td><td data-label="الثقة">{Number(r.confidence).toFixed(0)}%</td><td data-label="المبلغ" className="money-cell">{r.direction==='DEBIT'?'−':'+'}{formatSar(String(r.amount))}</td></tr>)}</tbody></table></div>
    </section></div></details>
  </main>;
}
