import Link from 'next/link';
import { requireAuthenticatedUser } from '@/auth/require-authenticated-user';
import { getFundingOverview } from '@/features/internal-funding/queries/get-funding-overview';
import { getRecoveryFutureForecast } from '@/features/internal-funding/queries/get-recovery-future-forecast';
import { Money, sumMoney } from '@/financial-engine/money';
import { formatSar } from '@/lib/format-money';
import { ActionDialog } from '@/components/overlays/action-dialog';
import { formatFinancialDate } from '@/lib/format-date';
import { beginFundingRecoveryAction, buildFundingRecoveryScheduleAction, createCategoryFundingRequestAction, createInternalFundingCaseAction, payRecoveryInstallmentAction } from './actions';
import { BankMessageDialogTrigger } from '@/components/bank-message-dialog';
import { LucideIcon } from '@/components/ui/lucide-icon';

const TYPE:Record<string,string>={TRIP:'رحلة',GOAL:'هدف',URGENT:'احتياج عاجل',CATEGORY:'تمويل بند',OTHER:'تمويل آخر'};
const STATUS:Record<string,string>={PLANNING:'تخطيط',ACTIVE:'قيد الاستخدام',RECOVERY:'قيد الاسترداد',CLOSED:'مغلق',CANCELLED:'ملغي'};
const SOURCE:Record<string,string>={EMERGENCY:'الطوارئ',INVESTMENT:'الاستثمار'};

export default async function InternalFundingPage({searchParams}:{searchParams:Promise<{error?:string;created?:string;categoryCreated?:string;recovery?:string;planned?:string;schedule?:string;paid?:string}>}){
  const user=await requireAuthenticatedUser();
  const [data,recoveryForecast,q]=await Promise.all([getFundingOverview(user.id),getRecoveryFutureForecast(user.id),searchParams]);
  const {cases,categories,sources,accounts,flexibleReliefs,recoverySchedule,budgetCategories}=data;
  const operatingAccounts=accounts.filter(a=>a.financialRole==='OPERATING');
  const totalUsed=sumMoney(cases.map((c)=>Money.parse(String(c.usedAmount??'0.00'))));
  const totalDebt=sumMoney(categories.map((c)=>Money.parse(String(c.remaining??'0.00')).max(Money.zero())));
  const emergencyGrowth=Money.parse(String(data.emergencyGrowth??'0.00'));
  const emergencyAccount=accounts.find(a=>a.financialRole==='EMERGENCY_FUND');

  return <main className="page-shell p47-internal-funding-page" dir="rtl">
    <header className="page-header p47-section-header"><div><p className="eyebrow">التخطيط والتمويل · التمويل الداخلي</p><div className="title-with-help"><h1>القروض والرحلات الممولة</h1></div></div><div className="button-row"><BankMessageDialogTrigger className="button-link">رسالة بنك</BankMessageDialogTrigger><Link className="button-link" href="/budget/optimizer">تحسين الخطة</Link></div></header>
    {q.error?<p className="error-banner" role="alert">{q.error}</p>:null}
    {q.created?<p className="success-banner">تم إنشاء التمويل. عند لصق الرسالة البنكية يمكنك ربط العملية به.</p>:null}
    {q.categoryCreated?<p className="success-banner">تم إنشاء تمويل البند من حساب الطوارئ بفائدة 10% وجدول سداد لا يتجاوز الحد الشهري الآمن الحالي.</p>:null}
    {q.recovery?<p className="success-banner">انتهت مرحلة الاستخدام. المبلغ غير المستخدم أعيد إلى رصيد المصدر الداخلي، وبدأت مرحلة الاسترداد.</p>:null}
    {q.planned?<p className="success-banner">تم حفظ مساهمة استرداد يدوية قديمة لهذه الدورة بدون خصم تلقائي.</p>:null}
    {q.schedule?<p className="success-banner">تم بناء جدول الاسترداد من الاستخدام الفعلي فقط.</p>:null}
    {q.paid?<p className="success-banner">تم تنفيذ دفعة الاسترداد كتحويل داخلي موثق؛ لم تُحتسب دخلًا أو مصروفًا جديدًا.</p>:null}

    <section className="p47-funding-kpis"><div><span>التمويلات</span><strong>{cases.length}</strong></div><div><span>المستخدم فعليًا</span><strong>{formatSar(totalUsed.toString())}</strong></div><div><span>عائد الطوارئ المحقق</span><strong>{formatSar(emergencyGrowth.toString())}</strong></div><div><span>المتبقي للاسترداد</span><strong>{formatSar(totalDebt.toString())}</strong></div></section>

    <section className="card p47-category-funding-request">
      <div className="section-title-row"><div><h2>طلب تمويل لبند</h2><p className="muted">حساب الطوارئ يعمل كبنك داخلي: يمول البند، ويستعيد الأصل مع زيادة 10% تعود كاملة إلى حساب الطوارئ.</p></div><LucideIcon name="landmark" size={24}/></div>
      {!emergencyAccount?<p className="error-banner">لا يوجد حساب طوارئ مفعّل. أنشئ حسابًا بدور «صندوق الطوارئ» أولًا.</p>:<form action={createCategoryFundingRequestAction} className="form-card p47-category-funding-form"><div className="form-grid">
        <label>اسم الطلب<input name="title" required maxLength={180} placeholder="مثال: صيانة السيارة"/></label>
        <label>البند<select name="categoryId" required defaultValue=""><option value="" disabled>اختر البند</option>{budgetCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label>مبلغ التمويل<input name="approvedAmount" inputMode="decimal" required placeholder="1000"/></label>
        <label>أقصى قسط شهري مريح<input name="maxMonthlyRepayment" inputMode="decimal" required placeholder="100"/></label>
        <div className="full p47-funding-policy-note"><LucideIcon name="info" size={20}/><span>يختبر النظام القسط مقابل فائض الخطة الحالي وخوارزمية توزيع الراتب. إذا كان سيضغط على الميزانية أو يحتاج أكثر من 36 دورة فلن يعتمد الطلب. الاسترداد يُعامل كبند مستقل ولا يستهلك مخصص البند الذي طلب التمويل.</span></div>
      </div><div className="button-row"><button className="primary-button" type="submit"><LucideIcon name="plus" size={20}/>إنشاء طلب التمويل</button><Link className="secondary-button" href="/budget/optimizer"><LucideIcon name="chart" size={20}/>فحص القدرة الشهرية</Link></div></form>}
    </section>

    <details className="ux-progressive-disclosure p75-secondary-section"><summary>إنشاء تمويل جديد</summary><div className="ux-progressive-disclosure__content"><section className="card p47-funding-create"><div className="section-title-row"><h2>تمويل جديد</h2></div>
      <form action={createInternalFundingCaseAction} className="form-card"><div className="form-grid">
        <label>اسم التمويل<input name="title" required maxLength={180} placeholder="مثال: رحلة جدة الأولى - الشتاء"/></label>
        <label>النوع<select name="caseType" defaultValue="TRIP"><option value="TRIP">رحلة</option><option value="GOAL">هدف</option><option value="URGENT">احتياج عاجل</option><option value="OTHER">آخر</option></select></label>
        <label>المدينة<input name="destinationCity" maxLength={120} placeholder="جدة"/></label>
        <label>الموسم<input name="seasonKey" maxLength={120} placeholder="الشتاء / رمضان / عيد الفطر"/></label>
        <label>المبلغ المعتمد<input name="approvedAmount" inputMode="decimal" required placeholder="1000"/></label>
        <label>حساب الطوارئ<select name="emergencyAccountId" defaultValue=""><option value="">بدون</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.bankName?`${a.bankName} · `:''}{a.name}</option>)}</select></label>
        <label>من الطوارئ<input name="emergencyAmount" inputMode="decimal" defaultValue="0"/></label>
        <label>المحفظة الاستثمارية<select name="investmentAccountId" defaultValue=""><option value="">بدون</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.bankName?`${a.bankName} · `:''}{a.name}</option>)}</select></label>
        <label>من الاستثمار<input name="investmentAmount" inputMode="decimal" defaultValue="0"/></label>
      </div><button className="primary-button" type="submit">إنشاء التمويل</button></form>
    </section></div></details>

    <section className="card p47-funding-ledger"><div className="section-title-row"><div><h2>قضايا التمويل</h2></div><span className="p47-count-badge">{cases.length}</span></div>{cases.length===0?<p className="muted">لا توجد تمويلات حتى الآن.</p>:<div className="p47-funding-case-list">{cases.map(c=>{
      const caseSources=sources.filter(s=>s.caseId===c.id);const caseDebt=sumMoney(categories.filter(x=>x.caseId===c.id).map((x)=>Money.parse(String(x.remaining??'0.00')).max(Money.zero())));const approved=Money.parse(String(c.approvedAmount??'0.00'));const used=Money.parse(String(c.usedAmount??'0.00'));const usagePercent=approved.isPositive()?Math.min(100,Number((used.minorUnits*10000n)/approved.minorUnits)/100):0;return <article key={c.id} className={`p47-funding-case is-${String(c.status).toLowerCase()}`}><div className="p47-funding-case-head"><div><span className="p47-status-pill">{STATUS[c.status]??c.status}</span><strong>{c.title}</strong><small>{TYPE[c.caseType]??c.caseType}{c.targetCategoryName?` · ${c.targetCategoryName}`:''}{[c.destinationCity,c.seasonKey].filter(Boolean).length?` · ${[c.destinationCity,c.seasonKey].filter(Boolean).join(' · ')}`:''}</small></div><div><span>المتبقي في القضية</span><strong>{formatSar(caseDebt.toString())}</strong></div></div><div className="p47-funding-usage"><div><span style={{width:`${usagePercent}%`}}/></div><small>استخدام {formatSar(String(c.usedAmount))} من {formatSar(String(c.approvedAmount))}</small></div><div className="p47-funding-case-metrics"><span>المعتمد<b>{formatSar(String(c.approvedAmount))}</b></span><span>المستخدم<b>{formatSar(String(c.usedAmount))}</b></span><span>الزيادة<b>{formatSar(String(c.growthContribution))}</b></span>{c.maxMonthlyRepayment?<span>حد القسط<b>{formatSar(String(c.maxMonthlyRepayment))}</b></span>:null}</div><div className="p47-funding-sources">{caseSources.map(src=><span key={src.id}><b>{SOURCE[src.sourceType]??src.sourceType}</b>{formatSar(String(src.usedAmount))} / {formatSar(String(src.approvedAmount))}</span>)}</div>{['PLANNING','ACTIVE'].includes(c.status)?<ActionDialog trigger="إنهاء الاستخدام وبدء الاسترداد" title="تأكيد بدء الاسترداد" description="سيتم إنهاء مرحلة الاستخدام والانتقال إلى مرحلة الاسترداد لهذا التمويل." size="sm" triggerClassName="secondary-button"><form action={beginFundingRecoveryAction}><input type="hidden" name="caseId" value={c.id}/><button className="primary-button" type="submit">تأكيد بدء الاسترداد</button></form></ActionDialog>:null}</article>})}</div>}</section>

    <details className="ux-progressive-disclosure p75-secondary-section"><summary>مديونية البنود</summary><div className="ux-progressive-disclosure__content"><section className="card p47-funding-debt"><div className="section-title-row"><h2>مديونية البنود الفعلية</h2></div>{categories.length===0?<p className="muted">بعد ربط مصروفات ممولة ستظهر هنا مسؤولية كل بند.</p>:<div className="dashboard-list">{categories.filter(c=>Money.parse(String(c.remaining??'0.00')).isPositive()).map(c=>{const owner=cases.find(item=>item.id===c.caseId);return <div key={`${c.caseId}-${c.categoryId}`}><div><strong>{c.categoryName}</strong><span>{owner?.title??'تمويل'} · الأصل {formatSar(String(c.principal))} · الزيادة {formatSar(String(c.growthContribution))} · المتبقي الفعلي {formatSar(String(c.remaining))}</span></div></div>})}</div>}</section></div></details>

    {recoveryForecast&&recoveryForecast.projectedCycles.length?<details className="ux-progressive-disclosure p75-secondary-section"><summary>توقع الاسترداد القادم</summary><div className="ux-progressive-disclosure__content"><section className="card"><div className="section-title-row"><h2>أثر الاسترداد على الدورات القادمة</h2></div><section className="statement-kpis"><div><span>إجمالي المتبقي المجدول</span><strong>{formatSar(recoveryForecast.totalOutstanding)}</strong></div><div><span>الأصل</span><strong>{formatSar(recoveryForecast.totalPrincipal)}</strong></div><div><span>الزيادة</span><strong>{formatSar(recoveryForecast.totalGrowth)}</strong></div><div><span>الدورات المتأثرة</span><strong>{recoveryForecast.projectedCycles.length}</strong></div></section><div className="dashboard-list">{recoveryForecast.projectedCycles.map(fc=><div key={fc.cycleIndex}><div><strong>{fc.label}{fc.projectedStartDate?` · ${formatFinancialDate(fc.projectedStartDate)}`:''}</strong><span>استرداد متوقع {formatSar(fc.totalAmount)} · أصل {formatSar(fc.principalAmount)} + زيادة {formatSar(fc.growthAmount)}</span>{fc.baselineExpectedIncome!=null?<small>إذا بقي الدخل المتوقع عند {formatSar(fc.baselineExpectedIncome)}: يتبقى بعد الاسترداد فقط {formatSar(fc.capacityAfterRecoveryOnly??'0.00')} قبل بقية الالتزامات والتخصيصات.</small>:<small>لا يوجد دخل مرجعي حالي كافٍ لحساب أثر الاسترداد على القدرة.</small>}{fc.sources.map(src=><small key={`${src.sourceId}:${src.installmentNumber}`}>{src.sourceType==='EMERGENCY'?'الطوارئ':'الاستثمار'} · {src.caseTitle} · دفعة {src.installmentNumber}: {formatSar(src.totalAmount)}{src.dueState==='OVERDUE'?' · متأخرة':src.dueState==='CURRENT'?' · مستحقة حاليًا':' · متوقعة'}</small>)}</div></div>)}</div></section></div></details>:null}

    <details className="ux-progressive-disclosure p75-recovery-work" open={cases.some(c=>c.status==='RECOVERY')}><summary>الاسترداد</summary><div className="ux-progressive-disclosure__content"><section className="card p47-recovery-schedule"><div className="section-title-row"><h2>جدول الاسترداد عبر الدورات</h2></div>
      {cases.filter(c=>c.status==='RECOVERY').map(c=>{const rows=recoverySchedule.filter(r=>r.caseId===c.id);if(!rows.length)return <div className="form-card" key={c.id}><strong>{c.title}</strong><p className="muted">هذا التمويل دخل مرحلة الاسترداد قبل إنشاء الجدول الجديد. أنشئ الجدول الآن من الاستخدام الفعلي المسجل.</p><form action={buildFundingRecoveryScheduleAction}><input type="hidden" name="caseId" value={c.id}/><button className="primary-button">بناء جدول الاسترداد</button></form></div>;
        const installmentNumbers=[...new Set(rows.map(r=>Number(r.installmentNumber)))].sort((a,b)=>a-b);return <div className="form-card" key={c.id}><div className="section-title-row"><div><strong>{c.title}</strong><span>{c.recoveryCycleCount} دورة · استراتيجية: استخدام فعلي نسبي</span></div><div><strong>{formatSar(sumMoney(rows.filter(r=>r.status==='PLANNED').map((r)=>Money.parse(String(r.totalAmount)))).toString())}</strong><small className="muted">متبقي مجدول</small></div></div>{installmentNumbers.map(n=>{const installmentRows=rows.filter(r=>Number(r.installmentNumber)===n);const sourceIds=[...new Set(installmentRows.map(r=>String(r.sourceId)))];return <div key={n} className="card"><h3>الدورة {n} من {c.recoveryCycleCount}</h3>{sourceIds.map(sourceId=>{const sr=installmentRows.filter(r=>String(r.sourceId)===sourceId);const first=sr[0];if(!first)return null;const total=sumMoney(sr.map((r)=>Money.parse(String(r.totalAmount))));const principal=sumMoney(sr.map((r)=>Money.parse(String(r.principalAmount))));const growth=sumMoney(sr.map((r)=>Money.parse(String(r.growthAmount))));const paid=sr.every(r=>r.status==='PAID');return <div key={sourceId} className="form-card"><div className="section-title-row"><div><strong>{SOURCE[first.sourceType]??first.sourceType} · {[first.sourceBankName,first.sourceAccountName].filter(Boolean).join(' · ')}</strong><span>أصل {formatSar(principal.toString())} · زيادة {formatSar(growth.toString())}</span><small>{sr.map(r=>`${r.categoryName}: ${formatSar(String(r.totalAmount))}`).join(' · ')}</small></div><strong>{formatSar(total.toString())}</strong></div>{paid?<p className="success-banner">مدفوع فعليًا{first.paidAt?` · ${formatFinancialDate(first.paidAt)}`:''}</p>:<form action={payRecoveryInstallmentAction} className="actions-row"><input type="hidden" name="caseId" value={c.id}/><input type="hidden" name="sourceId" value={sourceId}/><input type="hidden" name="installmentNumber" value={n}/><select name="fromAccountId" required defaultValue=""><option value="" disabled>اختر الحساب التشغيلي للسداد</option>{operatingAccounts.map(a=><option key={a.id} value={a.id}>{a.bankName?`${a.bankName} · `:''}{a.name}</option>)}</select><button className="primary-button">تنفيذ دفعة الاسترداد</button></form>}</div>})}</div>})}</div>})}
      {!cases.some(c=>c.status==='RECOVERY')?<p className="muted">لا توجد تمويلات في مرحلة الاسترداد حاليًا.</p>:null}
    </section></div></details>
  {flexibleReliefs.length?<section className="card"><h2>تخفيضات مرنة مرتبطة بخطط التمويل</h2><div className="dashboard-list">{flexibleReliefs.map(fr=><div key={fr.caseId+'|'+fr.categoryId}><div><strong>{fr.categoryName}</strong><span>{fr.previousAmount} → {fr.proposedAmount} ر.س · تحرير {fr.reliefAmount} ر.س</span></div>{fr.status==='REVISION_PENDING'?<Link href={`/budget/revise?plan=${fr.planId}&fundingCase=${fr.caseId}`}>مراجعة تعديل الميزانية</Link>:<span>لا يحتاج إجراء حاليًا</span>}</div>)}</div></section>:null}</main>;
}
