import { randomUUID } from 'node:crypto';
import { requireAuthenticatedUser } from '@/auth/require-authenticated-user';
import { listObligations } from '@/features/obligations/queries/list-obligations';
import { cancelObligationAction, createObligationAction, payObligationAction } from './actions';
import { Money, sumMoney } from '@/financial-engine/money';
import { formatSar } from '@/lib/format-money';
import { FocusedNextStep } from '@/components/ux/focused-next-step';
import { ActionDialog } from '@/components/overlays/action-dialog';
import { listAccounts } from '@/features/accounts/queries/list-accounts';
import { getUserOperationalDate } from '@/features/settings/queries/get-user-timezone';

const STATUS_LABELS: Record<string,string> = { OVERDUE:'متأخرة', DUE:'مستحقة الآن', UPCOMING:'قادمة', PAID:'مدفوعة', CANCELLED:'ملغاة' };
const RECURRENCE_LABELS: Record<string,string> = { ONCE:'مرة واحدة', MONTHLY:'شهري', QUARTERLY:'ربع سنوي', SEMI_ANNUAL:'نصف سنوي', ANNUAL:'سنوي' };
const ORDER = ['OVERDUE','DUE','UPCOMING','PAID'] as const;

export default async function ObligationsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const user = await requireAuthenticatedUser(); const query = await searchParams; const [obligations, accounts, today] = await Promise.all([listObligations(user.id), listAccounts(user.id), getUserOperationalDate(user.id)]);
  const activeAccounts = accounts.filter(a=>a.isActive);
  const open=obligations.filter(o=>['OVERDUE','DUE','UPCOMING'].includes(o.status));
  const reserved=sumMoney(open.filter(o=>o.isReserved).map(o=>Money.parse(o.amount)));
  const overdue=sumMoney(obligations.filter(o=>o.status==='OVERDUE').map(o=>Money.parse(o.amount)));
  return <main className="page-shell p47-resource-page" dir="rtl">
    <header className="p47-resource-header"><div><p className="eyebrow">الالتزامات</p><div className="title-with-help"><h1>الاستحقاقات</h1></div><p>ما يجب دفعه، متى يستحق، وما تم حجزه ماليًا قبل بقية الصرف.</p></div><ActionDialog title="إضافة التزام مالي" description="أنشئ الاستحقاق دون مغادرة صفحة الالتزامات." size="lg" triggerClassName="primary-link" trigger="إضافة التزام" defaultOpen={query.action==='add'}><form action={createObligationAction} className="form-grid"><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>اسم الالتزام<input name="name" required maxLength={160} placeholder="مثال: فاتورة الإنترنت"/></label><label>المبلغ الافتراضي<input name="defaultAmount" required inputMode="decimal" placeholder="0.00"/></label><label>التكرار<select name="recurrence" defaultValue="MONTHLY"><option value="ONCE">مرة واحدة</option><option value="MONTHLY">شهري</option><option value="QUARTERLY">ربع سنوي</option><option value="SEMI_ANNUAL">نصف سنوي</option><option value="ANNUAL">سنوي</option></select></label><label>أول تاريخ استحقاق<input name="firstDueDate" type="date" defaultValue={today} required/></label><label>الأولوية<input name="priority" type="number" min="1" placeholder="اختياري"/></label><label>الحساب المتوقع<select name="expectedAccountId"><option value="">غير محدد</option>{activeAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="primary-button" type="submit">إنشاء الالتزام</button></form></ActionDialog></header>
    <section className={`p74-focus-summary ${overdue.isPositive()?'is-danger':''}`}><div><span>الأولوية الحالية</span><strong>{overdue.isPositive()?`${formatSar(overdue)} متأخرة`: `${formatSar(reserved)} محجوزة للالتزامات`}</strong><small>{overdue.isPositive()?'ابدأ بالمتأخر أولًا، ثم المستحق الآن، ثم القادم.':'لا توجد متأخرات؛ تابع الاستحقاقات حسب ترتيبها الزمني.'}</small></div></section>
    {query.created==='1'?<section className="success-card"><strong>تم إنشاء الالتزام والاستحقاق الأول.</strong></section>:null}{query.paid==='1'?<section className="success-card"><strong>تم تسجيل السداد وتحرير الحجز.</strong></section>:null}{query.cancelled==='1'?<section className="success-card"><strong>تم إلغاء الاستحقاق القادم.</strong></section>:null}{typeof query.error==='string'?<section className="danger-zone"><strong>{query.error}</strong></section>:null}
    <section className="p47-resource-card"><div className="p47-section-heading"><div><span>التسلسل الزمني</span><h2>خريطة الاستحقاقات</h2></div><small>المتأخر ثم المستحق ثم القادم</small></div><div className="p47-obligation-timeline">{ORDER.flatMap(status=>obligations.filter(o=>o.status===status).map(o=><article className={`p47-obligation-item is-${status.toLowerCase()}`} key={o.id}><i/><div><div className="p47-chip-row"><span>{STATUS_LABELS[o.status]??o.status}</span><span>{RECURRENCE_LABELS[o.recurrence]??o.recurrence}</span>{o.isReserved?<span>محجوز ماليًا</span>:null}</div><h3>{o.name}</h3><small>{o.dueDate}{o.expectedAccountName?` · ${o.expectedAccountName}`:''}</small></div><div className="p47-obligation-money"><strong>{formatSar(o.amount)}</strong><div className="p49-resource-actions"><ActionDialog title={`تفاصيل ${o.name}`} trigger="التفاصيل"><div className="detail-list"><div><span>الحالة</span><strong>{STATUS_LABELS[o.status]??o.status}</strong></div><div><span>المبلغ</span><strong>{formatSar(o.amount)}</strong></div><div><span>الاستحقاق</span><strong>{o.dueDate}</strong></div><div><span>التكرار</span><strong>{RECURRENCE_LABELS[o.recurrence]??o.recurrence}</strong></div><div><span>الحساب المتوقع</span><strong>{o.expectedAccountName??'—'}</strong></div></div></ActionDialog>{['UPCOMING','DUE','OVERDUE'].includes(o.status)?<ActionDialog title={`تسجيل سداد ${o.name}`} description={`المبلغ المستحق ${formatSar(o.amount)}`} size="lg" trigger="تسجيل السداد"><form className="form-grid" action={payObligationAction}><input type="hidden" name="obligationOccurrenceId" value={o.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>المبلغ<input name="amount" value={o.amount} readOnly/></label><label>تاريخ السداد<input name="transactionDate" type="date" defaultValue={today} required/></label><label>الحساب<select name="accountId" defaultValue={o.expectedAccountId??''} required><option value="">اختر الحساب</option>{activeAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="primary-button" type="submit">تأكيد السداد</button></form></ActionDialog>:null}{o.status==='UPCOMING'?<ActionDialog title={`إلغاء ${o.name}`} description="لن يحذف السجل التاريخي." size="sm" trigger="إلغاء"><form action={cancelObligationAction}><input type="hidden" name="obligationOccurrenceId" value={o.id}/><input type="hidden" name="reason" value="إلغاء بواسطة المستخدم"/><button className="danger-button" type="submit">تأكيد الإلغاء</button></form></ActionDialog>:null}</div></div></article>))}{open.length===0?<div className="p47-empty-state"><strong>لا توجد استحقاقات مفتوحة</strong><span>الالتزامات القادمة ستظهر هنا تلقائيًا.</span></div>:null}</div></section>
    <FocusedNextStep href="/savings" title="التالي: الادخار" description="بعد ترتيب الاستحقاقات، انتقل إلى تنفيذ المبلغ المخصص للادخار."/>
  </main>;
}
