import Link from 'next/link';
import { requireAuthenticatedUser } from '@/auth/require-authenticated-user';
import { getSettingsOverview } from '@/features/settings/queries/get-settings-overview';
import { removeAvatarAction, revokeOtherSessionsAction, setRecurringObligationActiveAction, updateProfileSettingsAction } from './actions';
import { ActionDialog } from '@/components/overlays/action-dialog';
import { cookies } from 'next/headers';
import { AUTH_SESSION_COOKIE, getOwnerSecurityOverview } from '@/lib/auth/http-auth';
import { BrandLogoSettings } from '@/components/brand/brand-logo-settings';
const recurrenceLabels: Record<string,string> = { ONCE:'مرة واحدة',MONTHLY:'شهري',QUARTERLY:'ربع سنوي',SEMI_ANNUAL:'نصف سنوي',ANNUAL:'سنوي' };
export default async function SettingsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {const user=await requireAuthenticatedUser();const query=await searchParams;const token=(await cookies()).get(AUTH_SESSION_COOKIE)?.value??'';const [data,security]=await Promise.all([getSettingsOverview(user.id),getOwnerSecurityOverview({userId:user.id,currentSessionToken:token})]);const activeAccounts=data.accounts.filter(i=>i.isActive).length;const activeCategories=data.budgetCategories.filter(i=>i.isActive).length;const activeObligations=data.recurringObligations.filter(i=>i.isActive).length;return <main className="page-shell p47-resource-page" dir="rtl"><header className="p47-resource-header"><div><p className="eyebrow">إدارة النظام</p><div className="title-with-help"><h1>الإعدادات</h1></div></div><Link className="secondary-link" href="/dashboard">الرئيسية</Link></header>{query.saved==='1'?<section className="success-card"><strong>تم حفظ إعدادات الملف الشخصي.</strong></section>:null}{typeof query.error==='string'?<section className="danger-zone"><strong>{query.error}</strong></section>:null}
<BrandLogoSettings/><section className="p47-settings-hub"><article className="p47-resource-card p47-settings-profile"><div className="p47-section-heading"><div><span>الملف الشخصي</span><h2>الهوية والتوقيت</h2></div><ActionDialog title="تعديل الهوية والتوقيت" size="lg" trigger="تعديل"><form action={updateProfileSettingsAction} className="p47-settings-form"><label>الاسم المعروض<input name="displayName" maxLength={120} defaultValue={data.profile.displayName??''}/></label><label>البريد الإلكتروني<input value={user.email??''} readOnly/></label><label>العملة<input value="SAR — ريال سعودي" readOnly/></label><label>المنطقة الزمنية<input name="timezone" defaultValue={data.profile.timezone} required/></label><button className="primary-button">حفظ</button></form></ActionDialog></div><div className="detail-list"><div><span>الاسم</span><strong>{data.profile.displayName??'—'}</strong></div><div><span>البريد</span><strong>{user.email??'—'}</strong></div><div><span>المنطقة الزمنية</span><strong>{data.profile.timezone}</strong></div></div></article><aside className="p47-settings-navigation"><Link href="/settings/financial-buffer"><span>الاحتياطي المالي</span><strong>المتاح الآمن للصرف</strong></Link><Link href="/accounts"><span>الحسابات</span><strong>{activeAccounts}</strong></Link><Link href="/budget-categories"><span>بنود الميزانية</span><strong>{activeCategories}</strong></Link><Link href="/obligations"><span>الالتزامات المتكررة</span><strong>{activeObligations}</strong></Link><Link href="/merchants"><span>التجار والأسماء البديلة</span><strong>الأسماء البديلة</strong></Link><Link href="/decision-log"><span>سجل القرارات</span><strong>السجل</strong></Link></aside></section>
<section className="p47-resource-card p61-security-center"><div className="p47-section-heading"><div><span>الأمان</span><h2>أمان الحساب</h2></div><small>{security.emailVerified?'البريد موثّق':'البريد غير موثّق'}</small></div><div className="p61-security-grid"><article><span>الجلسات النشطة</span><strong>{security.activeSessionCount}</strong><small>{security.otherSessionCount?`${security.otherSessionCount} جلسة أخرى`:'هذه هي الجلسة الوحيدة'}</small></article><article><span>انتهاء الجلسة الحالية</span><strong>{security.currentSessionExpiresAt?new Date(security.currentSessionExpiresAt).toLocaleDateString('ar-SA'):'—'}</strong><small>{security.currentSessionCreatedAt?`بدأت ${new Date(security.currentSessionCreatedAt).toLocaleDateString('ar-SA')}`:'الجلسة الحالية غير معروفة'}</small></article><article><span>آخر تحديث لكلمة المرور</span><strong>{security.passwordUpdatedAt?new Date(security.passwordUpdatedAt).toLocaleDateString('ar-SA'):'—'}</strong><small>تغيير كلمة المرور يلغي الجلسات الأخرى تلقائيًا</small></article><article><span>حالة البريد</span><strong>{security.emailVerified?'موثّق':'غير موثّق'}</strong><small>{user.email??'—'}</small></article></div><div className="p61-security-actions"><form action={revokeOtherSessionsAction}><input type="hidden" name="returnTo" value="/settings"/><button className="secondary-button" disabled={security.otherSessionCount===0}>تسجيل الخروج من الجلسات الأخرى</button></form>{user.image?<form action={removeAvatarAction}><input type="hidden" name="returnTo" value="/settings"/><button className="secondary-button">إزالة صورة الحساب</button></form>:null}</div></section>
<details className="p74-secondary-disclosure"><summary>المراجع التشغيلية</summary><section className="p47-resource-card"><div className="p47-section-heading"><div><span>المراجع</span><h2>المراجع التشغيلية</h2></div></div><div className="p47-settings-reference-grid"><Link href="/accounts"><span>الحسابات</span><strong>{data.accounts.length}</strong><small>{activeAccounts} نشط</small></Link><Link href="/budget-categories"><span>بنود الميزانية</span><strong>{data.budgetCategories.length}</strong><small>{activeCategories} نشط</small></Link><Link href="/obligations"><span>قوالب الالتزامات</span><strong>{data.recurringObligations.length}</strong><small>{activeObligations} نشط</small></Link><Link href="/bank-statements"><span>كشوف الحساب</span><strong>Bank</strong><small>استيراد ومطابقة</small></Link><Link href="/internal-funding"><span>التمويل الداخلي</span><strong>10%</strong><small>الطوارئ والاستثمار</small></Link><Link href="/reports/learning"><span>تعلم النظام</span><strong>Learning</strong><small>السياق والقرارات</small></Link></div></section></details>
<details className="p74-secondary-disclosure"><summary>الالتزامات المتكررة</summary><section className="p47-resource-card"><div className="p47-section-heading"><div><span>الالتزامات</span><h2>الالتزامات المتكررة</h2></div><Link className="secondary-link" href="/obligations">إدارة الالتزامات</Link></div><div className="p47-settings-obligations">{data.recurringObligations.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.defaultAmount} ر.س · {recurrenceLabels[item.recurrence]??item.recurrence}{item.expectedAccountName?` · ${item.expectedAccountName}`:''}</span></div><ActionDialog title={`${item.isActive?'تعطيل':'إعادة تفعيل'} ${item.name}`} description="سيتم تغيير حالة القالب فقط دون المساس بالسجل التاريخي." size="sm" trigger={item.isActive?'تعطيل':'إعادة تفعيل'}><form action={setRecurringObligationActiveAction}><input type="hidden" name="templateId" value={item.id}/><input type="hidden" name="isActive" value={item.isActive?'false':'true'}/><button className={item.isActive?'danger-button':'primary-button'}>{item.isActive?'تأكيد التعطيل':'تأكيد إعادة التفعيل'}</button></form></ActionDialog></article>)}{data.recurringObligations.length===0?<div className="p47-empty-state"><strong>لا توجد قوالب</strong><span>أضف التزامًا متكررًا عند الحاجة.</span></div>:null}</div></section></details>
</main>}
