import { randomUUID } from 'node:crypto';
import { rawSql } from '@/infrastructure/db/client';
import type { BudgetCategoryInput } from '@/features/budget-categories/schemas/budget-category';
import type { BudgetCategoryView } from '@/features/budget-categories/types/budget-category';
import type { CategoryGroup, DefaultExpenseNature } from '@/domain/types';
function map(r:Record<string,unknown>):BudgetCategoryView{return {id:String(r.id),name:String(r.name),categoryGroup:String(r.category_group) as CategoryGroup,expenseNatureDefault:r.expense_nature_default?String(r.expense_nature_default) as DefaultExpenseNature:null,isEssential:Boolean(r.is_essential),isActive:Boolean(r.is_active),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
export class BudgetCategoryRepository{
 async listByUser(userId:string,includeInactive=false){const rows=await rawSql`select id,name,category_group,expense_nature_default,is_essential,is_active,created_at::text,updated_at::text from public.budget_categories where user_id=${userId} and (${includeInactive} or is_active=true) order by is_active desc,category_group,name`;return rows.map(r=>map(r as Record<string,unknown>));}
 async getById(userId:string,id:string){const rows=await rawSql`select id,name,category_group,expense_nature_default,is_essential,is_active,created_at::text,updated_at::text from public.budget_categories where user_id=${userId} and id=${id} limit 1`;return rows[0]?map(rows[0] as Record<string,unknown>):null;}
 async create(userId:string,input:BudgetCategoryInput){const id=randomUUID();const rows=await rawSql`insert into public.budget_categories(id,user_id,name,category_group,expense_nature_default,is_essential,is_active) values(${id},${userId},${input.name},${input.categoryGroup},${input.expenseNatureDefault},${input.isEssential},true) returning id,name,category_group,expense_nature_default,is_essential,is_active,created_at::text,updated_at::text`;return map(rows[0] as Record<string,unknown>);}
 async update(userId:string,id:string,input:BudgetCategoryInput){const rows=await rawSql`update public.budget_categories set name=${input.name},category_group=${input.categoryGroup},expense_nature_default=${input.expenseNatureDefault},is_essential=${input.isEssential} where user_id=${userId} and id=${id} returning id,name,category_group,expense_nature_default,is_essential,is_active,created_at::text,updated_at::text`;return rows[0]?map(rows[0] as Record<string,unknown>):null;}
 async deactivate(userId:string,id:string){const rows=await rawSql`update public.budget_categories set is_active=false where user_id=${userId} and id=${id} and is_active=true returning id`;return rows.length===1;}
 async seedDefaults(userId:string){const defaults=[['غذاء','ESSENTIAL','NECESSARY',true],['وقود','ESSENTIAL','NECESSARY',true],['اتصالات','ESSENTIAL','IMPORTANT',true],['مواصلات','ESSENTIAL','NECESSARY',true],['مطاعم','FLEXIBLE','OPTIONAL',false],['احتياجات منزلية','ESSENTIAL','IMPORTANT',true],['مصروف شخصي','FLEXIBLE','OPTIONAL',false]] as const;for(const d of defaults){await rawSql`insert into public.budget_categories(id,user_id,name,category_group,expense_nature_default,is_essential,is_active) values(${randomUUID()},${userId},${d[0]},${d[1]},${d[2]},${d[3]},true) on conflict do nothing`;}}
}
export const budgetCategoryRepository=new BudgetCategoryRepository();
