import { randomUUID } from 'node:crypto';
import { rawSql } from '@/infrastructure/db/client';
import { Money } from '@/financial-engine/money';
import { calculateEmergencyCoverage } from '@/financial-engine/emergency-coverage';
import type { EmergencyFundStatus, EmergencyAllocationStatus } from '@/domain/types';
import type { ConfigureEmergencyFundInput, EmergencyContributionInput, EmergencyWithdrawalInput } from '@/features/emergency/schemas/emergency';
import type { EmergencyFundSummary, EmergencyMovementResult } from '@/features/emergency/types/emergency';

function fundStatus(target:string|null,balance:string,hadMovement:boolean):EmergencyFundStatus{if(!target)return'NOT_CONFIGURED';const b=Money.parse(balance),t=Money.parse(target);if(b.isZero()&&hadMovement)return'DEPLETED';if(b.compare(t)>=0)return'FUNDED';return'BUILDING'}
function allocationStatus(allocated:string,actual:string,stored:EmergencyAllocationStatus):EmergencyAllocationStatus{if(stored==='CANCELLED')return stored;const a=Money.parse(allocated),x=Money.parse(actual);if(x.isZero())return'ALLOCATED';if(x.compare(a)>=0)return'TRANSFERRED';return'PARTIALLY_TRANSFERRED'}
export class EmergencyRepository{
 async configure(userId:string,input:ConfigureEmergencyFundInput){const rows=await rawSql`insert into public.emergency_funds(id,user_id,name,target_amount,status) values(${randomUUID()},${userId},${input.name},${input.targetAmount},'BUILDING') on conflict(user_id) do update set name=excluded.name,target_amount=excluded.target_amount,status=case when public.emergency_funds.status='DEPLETED' then 'DEPLETED' else 'BUILDING' end,updated_at=now() returning id`;return String(rows[0]?.id)}
 async summary(userId:string):Promise<EmergencyFundSummary|null>{const rows=await rawSql`select ef.id,ef.name,ef.target_amount::text,ef.status,
   coalesce(sum(case when em.movement_type='CONTRIBUTION' and em.posted_at is not null then em.amount when em.movement_type='WITHDRAWAL' and em.posted_at is not null then -em.amount else 0 end),0)::text balance,
   count(em.id)::int movement_count
   from public.emergency_funds ef left join public.emergency_movements em on em.emergency_fund_id=ef.id and em.user_id=ef.user_id where ef.user_id=${userId} group by ef.id limit 1`;
  if(!rows[0])return null;const r=rows[0];const target=r.target_amount?String(r.target_amount):null,balance=String(r.balance);const status=fundStatus(target,balance,Number(r.movement_count)>0);
  if(String(r.status)!==status) await rawSql`update public.emergency_funds set status=${status},updated_at=now() where id=${String(r.id)}::uuid and user_id=${userId}`;
  const ars=await rawSql`select ea.id,ea.planned_amount::text,ea.allocated_amount::text,ea.status,
   coalesce(sum(em.amount) filter(where em.movement_type='CONTRIBUTION' and em.posted_at is not null and em.cycle_id=ea.cycle_id),0)::text actual
   from public.emergency_allocations ea join public.financial_cycles c on c.id=ea.cycle_id and c.user_id=ea.user_id left join public.emergency_movements em on em.user_id=ea.user_id and em.emergency_fund_id=ea.emergency_fund_id
   where ea.user_id=${userId} and c.status='ACTIVE' group by ea.id order by ea.created_at desc limit 1`;
  let allocation=null;if(ars[0]){const a=ars[0];const rem=Money.parse(String(a.allocated_amount)).subtract(Money.parse(String(a.actual)));allocation={id:String(a.id),plannedAmount:String(a.planned_amount),allocatedAmount:String(a.allocated_amount),actualContributedAmount:String(a.actual),remainingToTransfer:rem.isNegative()?'0.00':rem.toString(),status:allocationStatus(String(a.allocated_amount),String(a.actual),String(a.status) as EmergencyAllocationStatus)}}
  let progressPercent:null|string=null;if(target){const t=Money.parse(target).minorUnits,b=Money.parse(balance).minorUnits;progressPercent=t>0n?((Number(b*10000n/t)/100).toFixed(2)):null}
  const baselineRows=await rawSql`select coalesce(sum(ba.planned_amount),0)::text essential_baseline
    from public.financial_plans p join public.budget_allocations ba on ba.plan_version_id=p.current_version_id and ba.user_id=p.user_id
    where p.user_id=${userId} and p.status in ('ACTIVE_PLAN','REVISED') and ba.allocation_type='ESSENTIAL'`;
  const essentialBaseline=Money.parse(String(baselineRows[0]?.essential_baseline??'0'));
  const coverage=calculateEmergencyCoverage(Money.parse(balance),essentialBaseline);
  return{emergencyFundId:String(r.id),name:String(r.name),targetAmount:target,currentBalance:balance,progressPercent,status,allocation,coverageMonths:coverage.coverageMonths,coverageMonthsStatus:coverage.status,targetPolicy:coverage.targetPolicy};
 }
 async movement(userId:string,input:EmergencyContributionInput|EmergencyWithdrawalInput,type:'CONTRIBUTION'|'WITHDRAWAL'):Promise<EmergencyMovementResult>{
  const existing=await rawSql`select id,amount::text,movement_type,posted_at::text from public.emergency_movements where user_id=${userId} and idempotency_key=${input.idempotencyKey} limit 1`;if(existing[0]){const e=existing[0];if(String(e.movement_type)!==type||String(e.amount)!==input.amount)throw new Error('IDEMPOTENCY_KEY_REUSED');const s=await this.summary(userId);if(!s)throw new Error('EMERGENCY_FUND_NOT_FOUND');const tx=await rawSql`select id,transaction_direction from public.transactions where emergency_movement_id=${String(e.id)}::uuid and user_id=${userId}`;return{movementId:String(e.id),outTransactionId:String(tx.find((x)=>x.transaction_direction==='OUT')?.id??''),inTransactionId:String(tx.find((x)=>x.transaction_direction==='IN')?.id??''),amount:String(e.amount),movementType:type,currentBalance:s.currentBalance,fundStatus:s.status,totalLiquidityChange:'0.00',postedAt:String(e.posted_at)}}
  const fund=await this.summary(userId);if(!fund||fund.emergencyFundId!==input.emergencyFundId||!fund.targetAmount)throw new Error('EMERGENCY_FUND_NOT_CONFIGURED');if(type==='WITHDRAWAL'&&Money.parse(input.amount).compare(Money.parse(fund.currentBalance))>0)throw new Error('EMERGENCY_WITHDRAWAL_EXCEEDS_BALANCE');if(type==='CONTRIBUTION'&&'emergencyAllocationId'in input&&input.emergencyAllocationId&&fund.allocation?.id===input.emergencyAllocationId&&Money.parse(input.amount).compare(Money.parse(fund.allocation.remainingToTransfer))>0)throw new Error('EMERGENCY_CONTRIBUTION_EXCEEDS_ALLOCATION');
  const movementId=randomUUID(),outId=randomUUID(),inId=randomUUID(),postedAt=new Date();const transactionType=type==='CONTRIBUTION'?'EMERGENCY_CONTRIBUTION':'EMERGENCY_WITHDRAWAL';const source=input.fromAccountId,dest=input.toAccountId;const reason=type==='WITHDRAWAL'?(input as EmergencyWithdrawalInput).reason:null;const emergencyType=type==='WITHDRAWAL'?(input as EmergencyWithdrawalInput).emergencyType:null;const allocationId=type==='CONTRIBUTION'?(input as EmergencyContributionInput).emergencyAllocationId??null:null;
  const res=await rawSql.transaction([
   rawSql`select id from public.emergency_funds where id=${input.emergencyFundId}::uuid and user_id=${userId} for update`,
   rawSql`insert into public.emergency_movements(id,user_id,emergency_fund_id,emergency_allocation_id,cycle_id,movement_type,from_account_id,to_account_id,amount,transaction_date,description,reason,emergency_type,idempotency_key,posted_at) select ${movementId},${userId},${input.emergencyFundId},${allocationId}::uuid,c.id,${type},${source},${dest},${input.amount},${input.transactionDate},${input.description??null},${reason},${emergencyType},${input.idempotencyKey},${postedAt} from public.financial_cycles c where c.user_id=${userId} and c.status='ACTIVE' and exists(select 1 from public.accounts a where a.id=${source}::uuid and a.user_id=${userId} and a.is_active=true) and exists(select 1 from public.accounts a where a.id=${dest}::uuid and a.user_id=${userId} and a.is_active=true) returning id`,
   rawSql`insert into public.transactions(id,user_id,cycle_id,account_id,transaction_type,status,amount,transaction_date,description,transaction_direction,emergency_fund_id,emergency_movement_id,idempotency_key,posted_at) select ${outId},${userId},cycle_id,from_account_id,${transactionType},'POSTED',amount,transaction_date,description,'OUT',emergency_fund_id,id,${input.idempotencyKey+':OUT'},${postedAt} from public.emergency_movements where id=${movementId} returning id`,
   rawSql`insert into public.transactions(id,user_id,cycle_id,account_id,transaction_type,status,amount,transaction_date,description,transaction_direction,emergency_fund_id,emergency_movement_id,idempotency_key,posted_at) select ${inId},${userId},cycle_id,to_account_id,${transactionType},'POSTED',amount,transaction_date,description,'IN',emergency_fund_id,id,${input.idempotencyKey+':IN'},${postedAt} from public.emergency_movements where id=${movementId} returning id`,
   ...(type==='WITHDRAWAL'?[rawSql`insert into public.emergency_withdrawal_details(id,transaction_id,reason,emergency_type) values(gen_random_uuid(),${outId},${reason},${emergencyType}) returning id`]:[])
  ]);if((res[1] as unknown[]).length!==1)throw new Error('EMERGENCY_MOVEMENT_PRECONDITION_FAILED');const s=await this.summary(userId);if(!s)throw new Error('EMERGENCY_FUND_NOT_FOUND');return{movementId,outTransactionId:outId,inTransactionId:inId,amount:input.amount,movementType:type,currentBalance:s.currentBalance,fundStatus:s.status,totalLiquidityChange:'0.00',postedAt:postedAt.toISOString()}
 }
}
export const emergencyRepository=new EmergencyRepository();
