import { Money } from '@/financial-engine/money';
import { rawSql, type SqlRow } from '@/infrastructure/db/client';

const goalEligibleReasons=new Set(['TRAVEL','OCCASION','MAINTENANCE','EXCEPTIONAL_PURCHASE','OTHER']);
const labels:Record<string,string>={VACATION:'إجازة',TRAVEL:'سفر',WORK_AWAY:'عمل خارج المنطقة',WITH_FAMILY:'إقامة عند الأهل',OCCASION:'مناسبة',GUESTS:'ضيوف',MAINTENANCE:'صيانة',FAMILY_CIRCUMSTANCE:'ظرف عائلي',HEALTH:'ظرف صحي',EXCEPTIONAL_PURCHASE:'شراء استثنائي',TEMPORARY_CHANGE:'تغير مؤقت',PERMANENT_CHANGE:'تغير دائم',OTHER:'سبب مخصص'};
export type GoalPatternRecommendation={key:string;reasonCode:string;reasonLabel:string;customReason:string|null;seasonCode:string|null;customSeasonName:string|null;cycleCount:number;categoryCount:number;categories:Array<{id:string;name:string;actual:string;planned:string}>;totalActual:string;totalPlanned:string;deviationAmount:string;deviationPercent:number|null;averageActualPerCycle:string;explicitRecurringContext:boolean;shouldConsiderGoal:boolean;linkedGoalId:string|null;linkedGoalName:string|null};
export async function getGoalPatternRecommendations(userId:string):Promise<GoalPatternRecommendation[]>{
 const rows=await rawSql`select fc.id::text cycle_id,ccc.category_id::text,bc.name category_name,reason.value reason_code,ccc.custom_reason,ccc.persistence,ccc.season_code,ccc.custom_season_name,ccs.planned_amount::text,ccs.actual_amount::text from public.cycle_category_contexts ccc join public.financial_cycles fc on fc.id=ccc.cycle_id and fc.user_id=ccc.user_id and fc.status='CLOSED' join public.budget_categories bc on bc.id=ccc.category_id and bc.user_id=ccc.user_id join public.cycle_snapshots cs on cs.user_id=ccc.user_id and cs.cycle_id=ccc.cycle_id join public.cycle_category_snapshots ccs on ccs.snapshot_id=cs.id and ccs.user_id=ccc.user_id and ccs.category_id=ccc.category_id cross join lateral jsonb_array_elements_text(ccc.reason_codes) reason(value) where ccc.user_id=${userId} and ccc.direction='HIGHER' order by cs.closed_at desc,bc.name`;
 const links=await rawSql`select l.reason_code,l.custom_reason,l.season_code,l.custom_season_name,l.goal_id::text,g.name goal_name from public.goal_context_pattern_links l join public.financial_goals g on g.id=l.goal_id and g.user_id=l.user_id where l.user_id=${userId} and l.status='ACTIVE' and g.status<>'CANCELLED'`;
 const keyOf=(r:SqlRow)=>[String(r.reason_code),String(r.reason_code)==='OTHER'?String(r.custom_reason??'').trim():'',String(r.season_code??''),String(r.season_code??'')==='CUSTOM'?String(r.custom_season_name??'').trim():''].join('|');
 const grouped=new Map<string,SqlRow[]>();for(const r of rows){const k=keyOf(r);const a=grouped.get(k)??[];a.push(r);grouped.set(k,a)}const linkMap=new Map((links).map(r=>[keyOf(r),r]));const out:GoalPatternRecommendation[]=[];
 for(const [key,items] of grouped){const first=items[0];if(!first)continue;const cycles=new Set(items.map(x=>String(x.cycle_id)));const cats=new Map<string,{id:string;name:string;actual:Money;planned:Money}>();let totalActual=Money.zero(),totalPlanned=Money.zero(),recurring=false;for(const i of items){const a=Money.parse(String(i.actual_amount)),p=Money.parse(String(i.planned_amount));totalActual=totalActual.add(a);totalPlanned=totalPlanned.add(p);recurring ||= i.persistence==='RECURRING'||i.persistence==='PERMANENT';const id=String(i.category_id),e=cats.get(id);if(e){e.actual=e.actual.add(a);e.planned=e.planned.add(p)}else cats.set(id,{id,name:String(i.category_name),actual:a,planned:p})}const reasonCode=String(first.reason_code),cycleCount=cycles.size,categoryCount=cats.size;const diff=totalActual.subtract(totalPlanned);const pct=totalPlanned.isZero()?null:Number((diff.minorUnits<0n?-diff.minorUnits:diff.minorUnits)*10000n/totalPlanned.minorUnits)/100;const linked=linkMap.get(key);out.push({key,reasonCode,reasonLabel:reasonCode==='OTHER'&&first.custom_reason?String(first.custom_reason):(labels[reasonCode]??reasonCode),customReason:first.custom_reason?String(first.custom_reason):null,seasonCode:first.season_code?String(first.season_code):null,customSeasonName:first.custom_season_name?String(first.custom_season_name):null,cycleCount,categoryCount,categories:[...cats.values()].map(c=>({id:c.id,name:c.name,actual:c.actual.toString(),planned:c.planned.toString()})),totalActual:totalActual.toString(),totalPlanned:totalPlanned.toString(),deviationAmount:diff.toString(),deviationPercent:pct,averageActualPerCycle:Money.fromMinorUnits(totalActual.minorUnits/BigInt(Math.max(1,cycleCount))).toString(),explicitRecurringContext:recurring,shouldConsiderGoal:goalEligibleReasons.has(reasonCode)&&(cycleCount>1||recurring||categoryCount>1),linkedGoalId:linked?String(linked.goal_id):null,linkedGoalName:linked?String(linked.goal_name):null})}
 return out.sort((a,b)=>Number(b.shouldConsiderGoal)-Number(a.shouldConsiderGoal)||b.cycleCount-a.cycleCount||b.categoryCount-a.categoryCount);
}
