import { redirect } from 'next/navigation';
import { getOnboardingStatus } from '@/features/onboarding/queries/get-onboarding-status';
import { getOnboardingIncomeDraft } from '@/features/onboarding/queries/get-onboarding-income-draft';
import { requireAuthenticatedUser } from '@/auth/require-authenticated-user';
import { setupFirstIncomeAction, updateOnboardingIncomeAction } from '../actions';
import { OnboardingStepNav } from '@/features/onboarding/components/onboarding-step-nav';

export default async function Page({searchParams}:{searchParams:Promise<{error?:string;edit?:string}>}){
 const u=await requireAuthenticatedUser();const s=await getOnboardingStatus(u.id);if(s.accountsCount<1)redirect('/onboarding/accounts');const q=await searchParams;const editing=q.edit==='1'&&Boolean(s.cycleId);if(s.cycleId&&s.expectedIncomeCount>0&&!editing)redirect('/onboarding/obligations');const d=s.cycleId?await getOnboardingIncomeDraft(u.id,s.cycleId):null;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh'}).format(new Date());
 return <main className="app-page onboarding-page" dir="rtl"><div className="page-shell narrow-shell p47-closure-page"><div className="onboarding-progress"><span>3 من 6</span><strong>إعداد الدخل</strong></div><OnboardingStepNav current="/onboarding/income"/><header className="page-header p47-closure-header"><div><p className="eyebrow">إعداد الدخل</p><div className="title-with-help"><h1>{editing?'تعديل الدخل والدورة':'الدخل المتوقع والدورة الأولى'}</h1></div></div></header>{q.error&&<p className="form-error" role="alert">{q.error}</p>}<section className="card"><form className="form-grid" action={editing?updateOnboardingIncomeAction:setupFirstIncomeAction}>{editing&&d?<input type="hidden" name="cycleId" value={d.cycleId}/>:null}
 <fieldset className="full onboarding-fieldset"><legend>1. الدورة المالية</legend><div className="form-grid"><label>اسم الدورة<input name="cycleName" required defaultValue={d?.cycleName??''} placeholder="مثال: دورة الراتب الحالية"/></label><label>تاريخ بداية الدورة<input name="startDate" type="date" required defaultValue={d?.startDate??today}/></label><label>تاريخ الراتب القادم<input name="expectedNextIncomeDate" type="date" required defaultValue={d?.expectedNextIncomeDate??''}/></label></div></fieldset>
 <fieldset className="full onboarding-fieldset"><legend>2. الدخل الأساسي</legend><div className="form-grid"><label>مصدر الدخل<input name="sourceName" required defaultValue={d?.sourceName??''} placeholder="الراتب"/></label><label>الدخل المتوقع<input name="expectedAmount" inputMode="decimal" required defaultValue={d?.expectedAmount??''} placeholder="10000.00"/></label><label>تاريخ الاستلام المتوقع<input name="expectedDate" type="date" required defaultValue={d?.expectedDate??''}/></label><label>نوع الدخل<select name="incomeKind" defaultValue={d?.incomeKind??'SALARY'}><option value="SALARY">راتب</option><option value="ADDITIONAL_INCOME">دخل إضافي</option><option value="BONUS">مكافأة</option><option value="OTHER">أخرى</option></select></label><label className="check-label"><input name="isPrimary" type="checkbox" defaultChecked={d?.isPrimary??true}/> هذا هو الدخل الأساسي</label></div></fieldset>
 <div className="full"><button className="primary-button" type="submit">{editing?'حفظ والعودة للخطة':'حفظ والمتابعة'}</button></div></form></section></div></main>}
