import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const checks=[];
const check=(name,ok)=>checks.push([name,Boolean(ok)]);
const nav=read('src/app/(protected)/navigation.ts');
const desktop=read('src/app/(protected)/desktop-top-nav.tsx');
const tablet=read('src/app/(protected)/tablet-top-nav.tsx');
const tx=read('src/app/(protected)/transactions/page.tsx');
const exp=read('src/app/(protected)/expenses/page.tsx');
const bank=read('src/app/(protected)/bank-operations/page.tsx');
const pkg=JSON.parse(read('package.json'));
check('version 0.45.18',pkg.version==='0.45.18');
check('nav calls ledger السجل المالي',nav.includes("label: 'السجل المالي'"));
check('desktop quick add bank message',desktop.includes('/bank-operations#add-message')&&!desktop.includes('href="/expenses" aria-label="إضافة مصروف جديد"'));
check('tablet quick add bank message',tablet.includes('/bank-operations#add-message')&&!tablet.includes('href="/expenses" aria-label="إضافة مصروف جديد"'));
check('ledger primary bank intake',tx.includes('href="/bank-operations#add-message"')&&tx.includes('<h1>السجل المالي</h1>'));
check('manual expense explicitly fallback',exp.includes('إدخال مصروف يدوي')&&exp.includes('تسجيل استثنائي'));
check('stale ISSUE-0002 removed from expense UI',!exp.includes('ISSUE-0002'));
check('bank page no stale P45.1 eyebrow',!bank.includes('P45.1 ·'));
for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'}: ${n}`);
if(checks.some(([,ok])=>!ok)) process.exit(1);
console.log(`P45.18 final UI/build-readiness verification: PASS (${checks.length} checks)`);
