import { Money } from '@/financial-engine/money';
const uuidLike=/^[0-9a-f-]{32,36}$/i, dateLike=/^\d{4}-\d{2}-\d{2}$/, amountLike=/^\d{1,16}(?:\.\d{1,2})?$/;
export type Validation<T>={success:true;data:T}|{success:false;message:string};
export interface CreateGoalInput{name:string;targetAmount:string;openingBalance?:string;startDate:string;targetDate?:string;priority?:number;idempotencyKey:string}
export interface AnalyzeGoalInput{targetAmount:string;currentBalance:string;targetDate?:string;priority?:number}
export interface GoalContributionInput{goalId:string;accountId:string;amount:string;transactionDate:string;idempotencyKey:string}
function nonnegative(v?:string){if(v===undefined||v==='')return '0.00';if(!amountLike.test(v))return null;try{const m=Money.parse(v);return m.isNegative()?null:m.toString()}catch{return null}}
function positive(v?:string){if(!v||!amountLike.test(v))return null;try{const m=Money.parse(v);return m.isPositive()?m.toString():null}catch{return null}}
export function validateCreateGoal(i:Partial<CreateGoalInput>):Validation<CreateGoalInput>{const n=i.name?.trim();if(!n||n.length>160)return{success:false,message:'اسم الهدف غير صالح.'};const target=positive(i.targetAmount);if(!target)return{success:false,message:'قيمة الهدف يجب أن تكون أكبر من صفر.'};const opening=nonnegative(i.openingBalance);if(opening===null)return{success:false,message:'الرصيد الافتتاحي لا يمكن أن يكون سالبًا.'};if(!i.startDate||!dateLike.test(i.startDate))return{success:false,message:'تاريخ بداية الهدف مطلوب.'};if(i.targetDate&&(!dateLike.test(i.targetDate)||i.targetDate<i.startDate))return{success:false,message:'تاريخ الهدف يجب ألا يسبق تاريخ البداية.'};if(i.priority!==undefined&&(!Number.isInteger(i.priority)||i.priority<1))return{success:false,message:'الأولوية يجب أن تكون رقمًا صحيحًا يبدأ من 1.'};if(!i.idempotencyKey?.trim()||i.idempotencyKey.trim().length>200)return{success:false,message:'مفتاح منع التكرار غير صالح.'};return{success:true,data:{name:n,targetAmount:target,openingBalance:opening,startDate:i.startDate,targetDate:i.targetDate||undefined,priority:i.priority,idempotencyKey:i.idempotencyKey.trim()}}}
export function validateAnalyzeGoal(i:Partial<AnalyzeGoalInput>):Validation<AnalyzeGoalInput>{const target=positive(i.targetAmount),current=nonnegative(i.currentBalance);if(!target||current===null)return{success:false,message:'بيانات الهدف المالية غير صالحة.'};if(i.targetDate&&!dateLike.test(i.targetDate))return{success:false,message:'تاريخ الهدف غير صالح.'};return{success:true,data:{targetAmount:target,currentBalance:current,targetDate:i.targetDate||undefined,priority:i.priority}}}
export function validateGoalContribution(i:Partial<GoalContributionInput>):Validation<GoalContributionInput>{if(!i.goalId||!uuidLike.test(i.goalId)||!i.accountId||!uuidLike.test(i.accountId))return{success:false,message:'الهدف أو الحساب غير صالح.'};const amount=positive(i.amount);if(!amount)return{success:false,message:'مبلغ المساهمة يجب أن يكون أكبر من صفر.'};if(!i.transactionDate||!dateLike.test(i.transactionDate))return{success:false,message:'تاريخ المساهمة مطلوب.'};if(!i.idempotencyKey?.trim()||i.idempotencyKey.trim().length>200)return{success:false,message:'مفتاح منع التكرار غير صالح.'};return{success:true,data:{goalId:i.goalId,accountId:i.accountId,amount,transactionDate:i.transactionDate,idempotencyKey:i.idempotencyKey.trim()}}}
